#!/usr/bin/php
<?php

if (php_sapi_name() !== 'cli') exit;
$command = explode(":", $argv[1]);
if(file_exists(__DIR__."/cli/{$command[0]}")){
    try {
        require __DIR__."/cli/{$command[0]}";
    } catch(\Exception $e) {
        die(new \Exception($e->getMessage(), (int)$e->getCode()));
    }
} else echo "Command '{$command[0]}' doesn't exists";
