#!/usr/bin/php
<?php
require './src/config/config.php';

if (php_sapi_name() !== 'cli') {
    exit;
}
$port = "8000";
if(isset($argv[2])) $port = $argv[2];

exec("composer install");
exec("composer dump-autoload");